'use client';

import { useState } from 'react';
import { X, Copy, Download, Check, FileText, Clock, Target } from 'lucide-react';

interface TranscriptionResult {
  transcript: string;
  confidence: number;
  duration: number;
  words?: Array<{
    word: string;
    start: number;
    end: number;
    confidence: number;
  }>;
  metadata?: {
    fileName: string;
    fileSize: number;
    mimeType: string;
    model: string;
    language: string;
  };
}

interface TranscriptModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: TranscriptionResult | null;
}

export default function TranscriptModal({ isOpen, onClose, result }: TranscriptModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !result) return null;

  const handleCopy = async () => {
    await navigator.clipboard.writeText(result.transcript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    // Create a more detailed transcript file
    const transcriptContent = `VoiceScript AI - Audio Transcription
=====================================

File: ${result.metadata?.fileName || 'Unknown'}
Duration: ${result.duration.toFixed(1)} seconds
Confidence: ${Math.round(result.confidence * 100)}%
Model: ${result.metadata?.model || 'nova-2'}
Language: ${result.metadata?.language || 'en-US'}
Transcribed: ${new Date().toLocaleString()}

TRANSCRIPT:
-----------
${result.transcript}

${result.words && result.words.length > 0 ? `
WORD-LEVEL TIMESTAMPS:
---------------------
${result.words.map(word => 
  `${word.start.toFixed(2)}s - ${word.end.toFixed(2)}s: "${word.word}" (${Math.round(word.confidence * 100)}%)`
).join('\n')}
` : ''}

Generated by VoiceScript AI
Powered by Deepgram Nova-2 Model`;

    const blob = new Blob([transcriptContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `transcript-${new Date().toISOString().slice(0, 19).replace(/:/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
      <div className="w-full max-w-4xl max-h-[90vh] bg-slate-900 border border-gray-700 rounded-2xl shadow-2xl glow-effect overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-700">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-xl bg-gradient-to-r from-cyan-600 to-purple-600">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <h3 className="text-xl font-semibold text-cyan-300">Transcription Complete</h3>
          </div>
          <button 
            onClick={onClose}
            className="p-2 hover:bg-gray-700 rounded-lg transition-colors"
          >
            <X className="h-5 w-5 text-gray-400" />
          </button>
        </div>
        
        {/* Stats */}
        <div className="p-6 border-b border-gray-700">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="flex items-center space-x-3 p-4 glass-effect rounded-xl">
              <div className="p-2 rounded-lg bg-green-600/20">
                <Target className="h-5 w-5 text-green-400" />
              </div>
              <div>
                <div className="text-2xl font-bold text-green-400">
                  {Math.round(result.confidence * 100)}%
                </div>
                <div className="text-sm text-gray-400">Accuracy</div>
              </div>
            </div>
            
            <div className="flex items-center space-x-3 p-4 glass-effect rounded-xl">
              <div className="p-2 rounded-lg bg-blue-600/20">
                <Clock className="h-5 w-5 text-blue-400" />
              </div>
              <div>
                <div className="text-2xl font-bold text-blue-400">
                  {result.duration.toFixed(1)}s
                </div>
                <div className="text-sm text-gray-400">Duration</div>
              </div>
            </div>
            
            <div className="flex items-center space-x-3 p-4 glass-effect rounded-xl">
              <div className="p-2 rounded-lg bg-purple-600/20">
                <FileText className="h-5 w-5 text-purple-400" />
              </div>
              <div>
                <div className="text-2xl font-bold text-purple-400">
                  {result.transcript.split(' ').length}
                </div>
                <div className="text-sm text-gray-400">Words</div>
              </div>
            </div>
            
            {result.metadata && (
              <div className="md:col-span-3 mt-4">
                <div className="flex items-center space-x-3 p-4 glass-effect rounded-xl">
                  <div className="p-2 rounded-lg bg-cyan-600/20">
                    <FileText className="h-5 w-5 text-cyan-400" />
                  </div>
                  <div className="flex-1">
                    <div className="text-lg font-bold text-cyan-400 truncate">
                      {result.metadata.fileName}
                    </div>
                    <div className="text-sm text-gray-400">
                      {(result.metadata.fileSize / (1024 * 1024)).toFixed(2)} MB • {result.metadata.mimeType}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
        
        {/* Transcript */}
        <div className="p-6 overflow-y-auto max-h-96">
          <div className="glass-effect rounded-xl p-6">
            <h4 className="text-lg font-semibold text-cyan-300 mb-4">Transcript</h4>
            <div className="text-gray-200 leading-relaxed whitespace-pre-wrap">
              {result.transcript}
            </div>
          </div>
        </div>
        
        {/* Actions */}
        <div className="p-6 border-t border-gray-700">
          <div className="flex flex-col sm:flex-row gap-3">
            <button 
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center space-x-2 px-6 py-3 bg-cyan-600 hover:bg-cyan-500 rounded-xl font-medium transition-all duration-300 glow-effect"
            >
              {copied ? (
                <>
                  <Check className="h-5 w-5" />
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-5 w-5" />
                  <span>Copy Text</span>
                </>
              )}
            </button>
            
            <button 
              onClick={handleDownload}
              className="flex-1 flex items-center justify-center space-x-2 px-6 py-3 bg-purple-600 hover:bg-purple-500 rounded-xl font-medium transition-all duration-300 glow-effect-purple"
            >
              <Download className="h-5 w-5" />
              <span>Download TXT</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}